language: node_js
node_js:
  - '14'
services:
  - mongodb
cache: yarn
branches:
  only:
    - master
env:
  global:
    - PORT=8000
    - MONGODB_URL=mongodb+srv://asenta:7fMXL1LTXDqjhkkn@trello-app.cgy9y.mongodb.net/main-board?retryWrites=true&w=majority
    - JWT_SECRET=thisisasamplesecret
    - JWT_ACCESS_EXPIRATION_MINUTES=30
    - JWT_REFRESH_EXPIRATION_DAYS=30
script:
  - yarn lint
